AWSTemplateFormatVersion: '2010-09-09'
Description: 'HIPAA-Compliant EC2 Auto Scaling Group with Application Load Balancer for BMC Application - Main Template using Nested Stacks'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed
  
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: First private subnet ID for EC2 instances
  
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Second private subnet ID for EC2 instances
  
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet ID for ALB (single public subnet in Workload OU)
  
  InstanceType:
    Type: String
    Default: t3.nano
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
    Description: EC2 instance type
  
  MinSize:
    Type: Number
    Default: 1
    Description: Minimum number of instances in the Auto Scaling Group
  
  MaxSize:
    Type: Number
    Default: 3
    Description: Maximum number of instances in the Auto Scaling Group
  
  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired number of instances in the Auto Scaling Group
  
  AMIId:
    Type: String
    Description: AMI ID for EC2 instances (Ubuntu 22.04 LTS or later recommended for SSM)
    Default: ''
  
  SSLCertificateARN:
    Type: String
    Description: ARN of the SSL certificate in ACM for HTTPS listener (required for HIPAA compliance)
  
  AllowedCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to access the ALB (restrict for HIPAA compliance)
  
  KMSKeyId:
    Type: String
    Default: ''
    Description: KMS Key ID for encryption (optional, uses default AWS managed key if not provided)
  
  EnableVPCFlowLogs:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable VPC Flow Logs for network traffic auditing (required for HIPAA)
  
  TemplateBucketName:
    Type: String
    Description: S3 bucket name where nested stack templates are stored
    Default: ''

Conditions:
  HasCustomAMI: !Not [!Equals [!Ref AMIId, '']]
  CreateKMSKey: !Equals [!Ref KMSKeyId, '']
  HasKMSKeyId: !Not [!Equals [!Ref KMSKeyId, '']]
  EnableFlowLogs: !Equals [!Ref EnableVPCFlowLogs, 'true']
  UseS3Templates: !Not [!Equals [!Ref TemplateBucketName, '']]

Resources:
  # KMS Stack
  KMSStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/kms.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        KMSKeyId: !Ref KMSKeyId
      TimeoutInMinutes: 5

  # Logging Stack
  LoggingStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/logging.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        VpcId: !Ref VpcId
        KMSKeyId: !If
          - CreateKMSKey
          - !GetAtt KMSStack.Outputs.KMSKeyId
          - !Ref KMSKeyId
        EnableVPCFlowLogs: !Ref EnableVPCFlowLogs
      DependsOn:
        - KMSStack
      TimeoutInMinutes: 5

  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/security-groups.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        VpcId: !Ref VpcId
        AllowedCIDR: !Ref AllowedCIDR
      TimeoutInMinutes: 5

  # IAM Stack
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/iam.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        EC2ApplicationLogsGroupArn: !GetAtt LoggingStack.Outputs.EC2ApplicationLogsGroupArn
        KMSKeyArn: !If
          - CreateKMSKey
          - !GetAtt KMSStack.Outputs.KMSKeyArn
          - !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKeyId}'
      DependsOn:
        - LoggingStack
        - KMSStack
      TimeoutInMinutes: 5

  # ALB Stack
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/alb.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        VpcId: !Ref VpcId
        PublicSubnet1Id: !Ref PublicSubnet1Id
        ALBSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroupId
        SSLCertificateARN: !Ref SSLCertificateARN
      DependsOn:
        - SecurityGroupsStack
      TimeoutInMinutes: 10

  # EC2 Stack
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/ec2.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        InstanceType: !Ref InstanceType
        AMIId: !Ref AMIId
        EC2InstanceProfileArn: !GetAtt IAMStack.Outputs.EC2InstanceProfileArn
        EC2SecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.EC2SecurityGroupId
        KMSKeyId: !If
          - CreateKMSKey
          - !GetAtt KMSStack.Outputs.KMSKeyId
          - !Ref KMSKeyId
        EC2ApplicationLogsGroupName: !GetAtt LoggingStack.Outputs.EC2ApplicationLogsGroupName
      DependsOn:
        - IAMStack
        - SecurityGroupsStack
        - LoggingStack
        - KMSStack
      TimeoutInMinutes: 5

  # Auto Scaling Stack
  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    Condition: UseS3Templates
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucketName}.s3.amazonaws.com/templates/autoscaling.yaml'
      Parameters:
        StackName: !Ref AWS::StackName
        PrivateSubnet1Id: !Ref PrivateSubnet1Id
        PrivateSubnet2Id: !Ref PrivateSubnet2Id
        LaunchTemplateId: !GetAtt EC2Stack.Outputs.LaunchTemplateId
        LaunchTemplateVersion: !GetAtt EC2Stack.Outputs.LaunchTemplateLatestVersion
        TargetGroupARN: !GetAtt ALBStack.Outputs.TargetGroupARN
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        DesiredCapacity: !Ref DesiredCapacity
      DependsOn:
        - EC2Stack
        - ALBStack
      TimeoutInMinutes: 10

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer (HTTPS endpoint)
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS
    Condition: UseS3Templates
  
  LoadBalancerARN:
    Description: ARN of the Application Load Balancer
    Value: !GetAtt ALBStack.Outputs.LoadBalancerARN
    Condition: UseS3Templates
  
  TargetGroupARN:
    Description: ARN of the Target Group
    Value: !GetAtt ALBStack.Outputs.TargetGroupARN
    Condition: UseS3Templates
  
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !GetAtt AutoScalingStack.Outputs.AutoScalingGroupName
    Condition: UseS3Templates
  
  EC2SecurityGroupId:
    Description: Security Group ID for EC2 instances
    Value: !GetAtt SecurityGroupsStack.Outputs.EC2SecurityGroupId
    Condition: UseS3Templates
  
  ALBSecurityGroupId:
    Description: Security Group ID for ALB
    Value: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroupId
    Condition: UseS3Templates
  
  KMSKeyId:
    Description: KMS Key ID used for encryption
    Value: !If
      - CreateKMSKey
      - !GetAtt KMSStack.Outputs.KMSKeyId
      - !Ref KMSKeyId
    Condition: UseS3Templates
  
  CloudWatchLogGroups:
    Description: CloudWatch Log Groups for HIPAA audit logging
    Value: !Sub '${LoggingStack.Outputs.EC2ApplicationLogsGroupName}, ${LoggingStack.Outputs.ALBAccessLogsGroupName}'
    Condition: UseS3Templates
  
  HIPAAComplianceNote:
    Description: HIPAA Compliance Features Enabled
    Value: 'Encryption at rest (EBS), Encryption in transit (HTTPS/TLS), CloudWatch Logs, VPC Flow Logs, SSM Session Manager, Restricted Security Groups, Ubuntu OS'
