AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Load Balancer Template for HIPAA-Compliant Infrastructure'

Parameters:
  StackName:
    Type: String
    Description: Stack name for resource naming
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where ALB will be deployed
  
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet ID for ALB
  
  ALBSecurityGroupId:
    Type: String
    Description: Security Group ID for ALB
  
  SSLCertificateARN:
    Type: String
    Description: ARN of the SSL certificate in ACM for HTTPS listener

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${StackName}-alb'
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: routing.http.x_amzn_tls_version_and_cipher_suite.enabled
          Value: 'true'
        - Key: routing.http.xff_client_port.enabled
          Value: 'true'
        - Key: deletion_protection.enabled
          Value: 'true'
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-alb'
        - Key: Compliance
          Value: HIPAA
        - Key: Application
          Value: BMC

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${StackName}-tg'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
        - Key: stickiness.enabled
          Value: 'false'
      Tags:
        - Key: Name
          Value: !Sub '${StackName}-tg'
        - Key: Compliance
          Value: HIPAA
        - Key: Application
          Value: BMC

  ALBHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref SSLCertificateARN
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

  ALBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer (HTTPS endpoint)
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${StackName}-alb-dns'
  
  LoadBalancerARN:
    Description: ARN of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerArn
    Export:
      Name: !Sub '${StackName}-alb-arn'
  
  TargetGroupARN:
    Description: ARN of the Target Group
    Value: !Ref ALBTargetGroup
    Export:
      Name: !Sub '${StackName}-tg-arn'
